using Emotion.GameDataLib;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading;

namespace Emotion.SourceGeneration
{
    [Generator]
    public class GameDataSourceGenerator : IIncrementalGenerator
    {
        private const string GameDataFolderSegment = "Assets/Data/";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<string> fileEntries = context.AdditionalTextsProvider
                .Where(IsGameDataFile)
                .Select(ParseEntry)
                .Where(entry => entry != null);

            context.RegisterSourceOutput(fileEntries, Emit);
        }

        private static bool IsGameDataFile(AdditionalText text)
        {
            string path = text.Path;
            if (string.IsNullOrEmpty(path)) return false;
            if (!path.EndsWith(".egd", StringComparison.OrdinalIgnoreCase)) return false;

            string normalized = path.Replace('\\', '/');
            return normalized.IndexOf(GameDataFolderSegment, StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static string ParseEntry(AdditionalText text, CancellationToken cancellationToken)
        {
            SourceText sourceText = text.GetText(cancellationToken);
            if (sourceText == null) return null;
            
            return sourceText.ToString();
        }

        private static void Emit(SourceProductionContext context, string text)
        {
            StringBuilder sb = new StringBuilder(2048);
            string fileId = GameDataGenerator.WriteClassDef(sb, text, out string generatedClass, out string dataId);

            string safeFileName = Helpers.GetSafeName(fileId);
            context.AddSource($"GeneratedGameData.{safeFileName}.g.cs", sb.ToString());

            WriteReflectorHandling(context, dataId, generatedClass);
        }

        private static void WriteReflectorHandling(SourceProductionContext context, string dataId, string generatedClass)
        {
            string safeName = Helpers.GetSafeName(generatedClass);
            generatedClass = $"global::{generatedClass}";

            StringBuilder sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by Emotion.SourceGeneration (GameDataSourceGenerator)");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Emotion.Standard.Reflector;");
            sb.AppendLine("using Emotion.Standard.Reflector.Handlers;");
            sb.AppendLine("using Emotion.Standard.Reflector.Handlers.Base;");
            sb.AppendLine("using Emotion.Standard.Reflector.Handlers.Specifics;");
            sb.AppendLine();
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace ReflectorGen;");
            sb.AppendLine();
            // We need to use another class-name rather than the default reflector format, as we might conflict with the main reflector generator
            // if the class is also defined in code.
            sb.AppendLine($"public static class GameDataGen_ReflectorData{safeName}");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    public static void LoadReflector()");
            sb.AppendLine("    {");
            // If our registration is executed second we don't want to overwrite the reflector handler generated by the main reflector generator,
            // since it will contain fields defined in the code.
            sb.AppendLine($"       if (ReflectorEngine.GetTypeHandler<{generatedClass}>() != null) return;");
            sb.AppendLine($"       ReflectorEngine.RegisterTypeHandler(new ComplexTypeHandler<{generatedClass}>(");
            sb.AppendLine($"           () => new {generatedClass}(),");
            sb.AppendLine($"           \"{dataId}\", null,");
            sb.AppendLine("           null");
            sb.AppendLine("       ));");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"RFLC.{Helpers.GetFileNameSafeHash(safeName)}.g.cs", sb.ToString());
        }
    }
}
