<Project ToolsVersion="Current">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NoWarn>1701;1702;1591;1734;IDE0001;IDE0002;IDE0049</NoWarn>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <Nullable>enable</Nullable>
        <DefineConstants>$(DefineConstants);WEB</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <StaticWebAssetBasePath>Emotion</StaticWebAssetBasePath>
        <PublishAot>false</PublishAot>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    </PropertyGroup>

    <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.Razor" />
    <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.Razor" />

    <ItemGroup>
        <SupportedPlatform Include="browser" />
        <ProjectReference Include="..\Emotion.SourceGeneration\Emotion.SourceGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <IsTrimmable>true</IsTrimmable>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <!-- Don't include other platform files -->
    <ItemGroup>
        <Compile Remove="Core\Platform\Implementation\Android\**\*.cs" />
        <Compile Remove="Core\Platform\Implementation\Win32\**\*.cs" />
        <Compile Remove="Core\Platform\Implementation\CommonDesktop\**\*.cs" />
    </ItemGroup>

    <!-- Libraries Code Include -->
    <ItemGroup>
        <Compile Remove="Core\Platform\Implementation\OpenAL\**\*.cs" />
        <Compile Remove="Core\Platform\Implementation\GlfwImplementation\**\*.cs" />
        <Compile Remove="Core\Platform\Implementation\EglAngle\**\*.cs" />
        <Compile Remove="Standard\Parsers\Assimp\**\*.cs" />
    </ItemGroup>

    <!-- Don't include incompatible Emotion parts -->
    <ItemGroup>
        <Compile Remove="Network\_Old\**\*.cs" />
        <Compile Remove="Core\Systems\Scripting\**\*.cs" />
        <Compile Remove="Editor\RuntimeCodeGen\**\*.cs" />
        <Compile Remove="Core\Utility\Profiling\RenderDoc\**\*.cs" />
        <Compile Remove="Testing\**\*.cs" />
        <Compile Include="Testing\Assert.cs" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Assets\**\*.*">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
    </ItemGroup>
</Project>
