namespace Emotion.Standard.Logging
{
    public static class MessageSource
    {
        // Engine and modules
        public static string Engine = "Engine";
        public static string StdErr = "StdErr";
        public static string Renderer = "Renderer";
        public static string GL = "GL"; // Sent by the renderer and graphics related objects.
        public static string ShaderSource = "ShaderSource"; // Sent by the ShaderFactory - is spammy and contains shader source code.
        public static string AssetLoader = "AssetLoader";
        public static string SceneManager = "SceneManager";
        public static string ScriptingEngine = "ScriptingEngine";
        public static string Platform = "Platform";
        public static string Audio = "Audio";

        public static string Other = "Other";

        // Specific
        public static string ImagePng = "ImagePng";
        public static string Win32 = "Win32";
        public static string Wgl = "Wgl";
        public static string WGallium = "Win32-Gallium";
    }

    //public enum MessageSource
    //{
    //    /// <summary>
    //    /// Internal engine logs.
    //    /// </summary>
    //    Engine,

    //    /// <summary>
    //    /// Logs by the host.
    //    /// </summary>
    //    Host,

    //    /// <summary>
    //    /// Logs by the cross platform bootstrapper.
    //    /// </summary>
    //    Bootstrap,

    //    /// <summary>
    //    /// Logs by the graphics manager and other GL related functionality.
    //    /// </summary>
    //    GL,

    //    /// <summary>
    //    /// Logs by the ScriptingEngine module.
    //    /// </summary>
    //    ScriptingEngine,

    //    /// <summary>
    //    /// Logs by the SceneManager module.
    //    /// </summary>
    //    SceneManager,

    //    /// <summary>
    //    /// Logs by the AssetLoader module.
    //    /// </summary>
    //    AssetLoader,

    //    /// <summary>
    //    /// Logs by the InputManager module.
    //    /// </summary>
    //    Input,

    //    /// <summary>
    //    /// Logs by the renderer.
    //    /// </summary>
    //    Renderer,

    //    /// <summary>
    //    /// Logs by the sound manager.
    //    /// </summary>
    //    SoundManager,

    //    /// <summary>
    //    /// Other unidentified logs.
    //    /// </summary>
    //    Other,

    //    /// <summary>
    //    /// Submitted exceptions. Logged by the ErrorHandler.
    //    /// </summary>
    //    StdErr,

    //    /// <summary>
    //    /// Logs generated by the test run application.
    //    /// </summary>
    //    TestRunner,

    //    // Emotion Legacy
    //    Debugger,
    //    FileManager,

    //    // User
    //    Game,
    //    UIController,

    //    // Other
    //    StdOut
    //}
}