name: CI-Linux

on: [push]

jobs:
  build-n-run-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Build Everything
      run: |
        dotnet --info
        dotnet publish Tests -c DebugUnix64 -r linux-x64 -o Tests/bin/linux --self-contained true
    - name: Run Tests
      run: |
        cd ./Tests/bin/linux
        ls .
        ./Tests
    - name: Upload Test Artifact
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: Test Result Artifact
        path: Tests/bin/linux/TestResults
