name: CI-Linux

on: [push]

jobs:
  build-n-run-tests:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@master
    - uses: openrndr/setup-opengl@v1.1
    - name: Build Everything
      run: |
        dotnet --info
        dotnet publish Tests -c DebugUnix64 -r linux-x64 -o Tests/bin/linux --self-contained true
    - name: Run Tests
      run: |
        cd ./Tests/bin/linux
        LD_LIBRARY_PATH=../../../mesa-18.2.3/usr/local/lib/x86_64-linux-gnu GALLIUM_DRIVER=swr xvfb-run sudo ./Tests
    - name: Upload Test Artifact
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: Test Result Artifact
        path: Tests/bin/linux/TestResults
