name: CI-Linux

on:
  push:
    branches:
      - master

jobs:
  build-n-run-tests:

    runs-on: self-hosted
    
    steps:
    - name: Pull, Build, and Run Tests
      run: |
        git clean -fxd
        git pull
        dotnet publish Tests -c DebugUnix64 -r linux-x64 -o Tests/bin/linux --self-contained true
        cd ./Tests/bin/linux
        ./Tests
    - name: Upload Test Artifact
      if: always()
      uses: actions/upload-artifact@master
      with:
        name: Test Result Artifact
        path: Tests/bin/linux/TestResults
