name: PublishNuget

on:
  push:
    branches:
      - master

jobs:
  build-n-run-tests:

    runs-on: windows-2019
    
    steps:
    - name: Run publishing script
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: |
        dotnet tool install -g dotnet-script
        dotnet script PublishNuget.cs