#region Using

using Khronos;

#endregion

// 2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

namespace OpenGL
{
    public partial class Gl
    {
        #region Known Versions Constants

        /// <summary>
        /// Version for OpenGL 1.0 API.
        /// </summary>
        public static readonly KhronosVersion Version100 = new KhronosVersion(1, 0, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 1.1 API.
        /// </summary>
        public static readonly KhronosVersion Version110 = new KhronosVersion(1, 1, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 1.2 API.
        /// </summary>
        public static readonly KhronosVersion Version120 = new KhronosVersion(1, 2, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 1.3 API.
        /// </summary>
        public static readonly KhronosVersion Version130 = new KhronosVersion(1, 3, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 1.4 API.
        /// </summary>
        public static readonly KhronosVersion Version140 = new KhronosVersion(1, 4, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 1.5 API.
        /// </summary>
        public static readonly KhronosVersion Version150 = new KhronosVersion(1, 5, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 2.0 API.
        /// </summary>
        public static readonly KhronosVersion Version200 = new KhronosVersion(2, 0, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 2.1 API.
        /// </summary>
        public static readonly KhronosVersion Version210 = new KhronosVersion(2, 1, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 3.0 API.
        /// </summary>
        public static readonly KhronosVersion Version300 = new KhronosVersion(3, 0, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 3.1 API.
        /// </summary>
        public static readonly KhronosVersion Version310 = new KhronosVersion(3, 1, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 3.2 API.
        /// </summary>
        public static readonly KhronosVersion Version320 = new KhronosVersion(3, 2, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 3.3 API.
        /// </summary>
        public static readonly KhronosVersion Version330 = new KhronosVersion(3, 3, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.0 API.
        /// </summary>
        public static readonly KhronosVersion Version400 = new KhronosVersion(4, 0, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.1 API.
        /// </summary>
        public static readonly KhronosVersion Version410 = new KhronosVersion(4, 1, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.2 API.
        /// </summary>
        public static readonly KhronosVersion Version420 = new KhronosVersion(4, 2, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.3 API.
        /// </summary>
        public static readonly KhronosVersion Version430 = new KhronosVersion(4, 3, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.4 API.
        /// </summary>
        public static readonly KhronosVersion Version440 = new KhronosVersion(4, 4, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.5 API.
        /// </summary>
        public static readonly KhronosVersion Version450 = new KhronosVersion(4, 5, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL 4.6 API.
        /// </summary>
        public static readonly KhronosVersion Version460 = new KhronosVersion(4, 6, KhronosVersion.API_GL);

        /// <summary>
        /// Version for OpenGL ES 1.0 API.
        /// </summary>
        public static readonly KhronosVersion Version100Es = new KhronosVersion(1, 0, KhronosVersion.API_GLES1);

        /// <summary>
        /// Version for OpenGL ES 2.0 API.
        /// </summary>
        public static readonly KhronosVersion Version200Es = new KhronosVersion(2, 0, KhronosVersion.API_GLES2);

        /// <summary>
        /// Version for OpenGL ES 3.0 API.
        /// </summary>
        public static readonly KhronosVersion Version300Es = new KhronosVersion(3, 0, KhronosVersion.API_GLES2);

        /// <summary>
        /// Version for OpenGL ES 3.1 API.
        /// </summary>
        public static readonly KhronosVersion Version310Es = new KhronosVersion(3, 1, KhronosVersion.API_GLES2);

        /// <summary>
        /// Version for OpenGL ES 3.2 API.
        /// </summary>
        public static readonly KhronosVersion Version320Es = new KhronosVersion(3, 2, KhronosVersion.API_GLES2);

        #endregion
    }
}